### ISSUE TITLE
Link Skyblog fanfiction archives

### ISSUE THREAD

**Issue by stickgirl512** [bohwaz/skyblog-archiver#3]
I need to find those links in the Skyblog archive :

https://akihiko-asuka.skyrock.com/3225015237-O-S-Yaoi-C-L-Une-attache.html
https://fan2fiction.skyrock.com/214534285-Akujunkan.html
https://fan2fiction.skyrock.com/215112664-Akujunkan2.html
https://fan2fiction.skyrock.com/216356416-Akujunkan3.html

**Comment by bohwaz** [comment]
Skyblog is closed down.
